# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

pr:
  branches:
    include:
    - master
  paths:
    include:
    - '*'
    exclude:
    - 'tests'
    - 'devops'
    - README.md

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python38:
      python.version: '3.8'

steps:
- task: FileTransform@1
  displayName: 'Insert credentials to config.json'
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)'
    fileType: json
    targetFiles: config.json

- task: UsePythonVersion@0
  displayName: 'Use Python >=3.7.4'
  inputs:
    versionSpec: '>=3.7.4'
    addToPath: true

- script: python -m pip install --upgrade pip setuptools wheel
  displayName: 'Install tools'

- script: 'pip install -r requirements.txt'
  displayName: 'Install dependencies'

- script: |
    pip install pytest
    pip install pytest-cov
    pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/test-results.xml'
  inputs:
    testResultsFiles: '**/test-results.xml'
    testRunTitle: 'Python $(python.version)'


#Multi-configuration and multi-agent job options are not exported to YAML. Configure these options using documentation guidance: https://docs.microsoft.com/vsts/pipelines/process/phases






